 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [06/Oct/2020 10:43:51] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 10:43:51] "[37mGET /expense_data?_=1601981031577 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 10:43:51] "[37mGET /current_expense_data?_=1601981031578 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 10:44:23] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 10:44:24] "[37mGET /expense_data?_=1601981063705 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 10:44:24] "[37mGET /current_expense_data?_=1601981063706 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [06/Oct/2020 11:41:36] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 11:41:37] "[37mGET /expense_data?_=1601984496503 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 11:41:37] "[37mGET /current_expense_data?_=1601984496504 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [06/Oct/2020 12:01:44] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:01:45] "[37mGET /expense_data?_=1601985704713 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:01:45] "[37mGET /current_expense_data?_=1601985704714 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:01:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.91 - - [06/Oct/2020 12:02:03] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:02:04] "[37mGET /expense_data?_=1601985723709 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:02:04] "[37mGET /current_expense_data?_=1601985723710 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:04:12] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:04:13] "[37mGET /expense_data?_=1601985852826 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:04:13] "[37mGET /current_expense_data?_=1601985852827 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:07:51] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:07:51] "[37mGET /expense_data?_=1601986071162 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:07:51] "[37mGET /current_expense_data?_=1601986071163 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:08:39] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:08:39] "[37mGET /expense_data?_=1601986119113 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:08:39] "[37mGET /current_expense_data?_=1601986119114 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [06/Oct/2020 12:13:31] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:13:31] "[37mGET /expense_data?_=1601986411150 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:13:31] "[37mGET /current_expense_data?_=1601986411151 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:06] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:06] "[37mGET /expense_data?_=1601986446332 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:06] "[37mGET /current_expense_data?_=1601986446333 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:12] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:12] "[37mGET /expense_data?_=1601986451897 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:12] "[37mGET /current_expense_data?_=1601986451898 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:40] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:40] "[37mGET /expense_data?_=1601986479963 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:40] "[37mGET /current_expense_data?_=1601986479964 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:43] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:43] "[37mGET /expense_data?_=1601986482992 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:43] "[37mGET /current_expense_data?_=1601986482993 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:44] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:44] "[37mGET /expense_data?_=1601986484233 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:14:44] "[37mGET /current_expense_data?_=1601986484234 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [06/Oct/2020 12:21:30] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:21:36] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:21:36] "[37mGET /expense_data?_=1601986895983 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:21:37] "[37mGET /current_expense_data?_=1601986895984 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:23:54] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:23:55] "[37mGET /expense_data?_=1601987034625 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:23:55] "[37mGET /current_expense_data?_=1601987034626 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:24:57] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:24:58] "[37mGET /expense_data?_=1601987097710 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:24:58] "[37mGET /current_expense_data?_=1601987097711 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:26:45] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:26:45] "[37mGET /expense_data?_=1601987204992 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:26:45] "[37mGET /current_expense_data?_=1601987204993 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:29:54] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:29:54] "[37mGET /expense_data?_=1601987394253 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:29:54] "[37mGET /current_expense_data?_=1601987394254 HTTP/1.1[0m" 200 -
Traceback (most recent call last):
  File "main_mobile.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
 * Serving Flask app "main_mobile" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "main_mobile.py", line 141, in <module>
    app.run(host = '0.0.0.0',debug=True,port=5003)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "main_mobile" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5003/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [06/Oct/2020 12:31:40] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:31:40] "[37mGET /expense_data?_=1601987500492 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:31:40] "[37mGET /current_expense_data?_=1601987500493 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:31:49] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:31:49] "[37mGET /expense_data?_=1601987508811 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:31:49] "[37mGET /current_expense_data?_=1601987508812 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:32:39] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:32:44] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:32:44] "[37mGET /expense_data?_=1601987564299 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:32:44] "[37mGET /current_expense_data?_=1601987564300 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:38:57] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:39:02] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:39:02] "[37mGET /expense_data?_=1601987942372 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:39:02] "[37mGET /current_expense_data?_=1601987942373 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [06/Oct/2020 12:42:30] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:42:35] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:42:35] "[37mGET /expense_data?_=1601988155501 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 12:42:35] "[37mGET /current_expense_data?_=1601988155502 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 14:35:47] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 14:35:52] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 14:35:52] "[37mGET /expense_data?_=1601994951475 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 14:35:52] "[37mGET /current_expense_data?_=1601994951476 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 14:55:59] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 14:55:59] "[37mGET /expense_data?_=1601996158001 HTTP/1.1[0m" 200 -
183.83.147.91 - - [06/Oct/2020 14:55:59] "[37mGET /current_expense_data?_=1601996158002 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:07:22] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:07:22] "[37mGET /expense_data?_=1602040041314 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:07:22] "[37mGET /current_expense_data?_=1602040041315 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:09:37] "[37mGET /expense_data?_=1602040175521 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:09:37] "[37mGET /current_expense_data?_=1602040175522 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:10:08] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:10:08] "[37mGET /expense_data?_=1602040207235 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 03:10:08] "[37mGET /current_expense_data?_=1602040207236 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 05:19:21] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 05:19:22] "[37mGET /expense_data?_=1602047960614 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 05:19:22] "[37mGET /current_expense_data?_=1602047960615 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [07/Oct/2020 07:31:16] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 07:31:17] "[37mGET /expense_data?_=1602055877120 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 07:31:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.91 - - [07/Oct/2020 07:31:17] "[37mGET /current_expense_data?_=1602055877121 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.91 - - [07/Oct/2020 07:32:07] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 07:32:07] "[37mGET /expense_data?_=1602055927205 HTTP/1.1[0m" 200 -
183.83.147.91 - - [07/Oct/2020 07:32:07] "[37mGET /current_expense_data?_=1602055927206 HTTP/1.1[0m" 200 -
74.120.14.35 - - [07/Oct/2020 11:02:50] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03!\x87')
74.120.14.35 - - [07/Oct/2020 11:02:50] "[35m[1m {  w!	ÌV]¤qùsdÔQZÞæ&^ékäõ½vï[0m" HTTPStatus.BAD_REQUEST -
74.120.14.35 - - [07/Oct/2020 11:02:51] "[37mGET / HTTP/1.1[0m" 200 -
74.120.14.35 - - [07/Oct/2020 11:02:52] "[37mGET / HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:27:25] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:27:31] "[37mGET / HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:27:31] "[37mGET /expense_data?_=1602073649842 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:27:31] "[37mGET /current_expense_data?_=1602073649843 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:28:12] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:28:18] "[37mGET / HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:28:18] "[37mGET /expense_data?_=1602073696864 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:28:18] "[37mGET /current_expense_data?_=1602073696865 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:32:32] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:32:37] "[37mGET / HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:32:37] "[37mGET /expense_data?_=1602073956108 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:32:37] "[37mGET /current_expense_data?_=1602073956109 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:33:01] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:33:06] "[37mGET / HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:33:06] "[37mGET /expense_data?_=1602073985389 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 12:33:06] "[37mGET /current_expense_data?_=1602073985390 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 13:00:35] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 13:00:41] "[37mGET / HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 13:00:41] "[37mGET /expense_data?_=1602075639969 HTTP/1.1[0m" 200 -
157.47.112.199 - - [07/Oct/2020 13:00:41] "[37mGET /current_expense_data?_=1602075639970 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
167.248.133.36 - - [07/Oct/2020 14:16:26] code 400, message Bad request syntax ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03\x80p\x91\x8e\x93\x17²\x06jGÇHÌm\x1f¾p@ê¶\x84ãì\x85ÝH-·¬I\x1f,\x00\x00\x1aÀ/À+À\x11À\x07À\x13À\tÀ\x14À')
167.248.133.36 - - [07/Oct/2020 14:16:26] "[35m[1m {  wp²jGÇHÌm¾p@ê¶ãìÝH-·¬I,  À/À+ÀÀÀÀ	ÀÀ[0m" HTTPStatus.BAD_REQUEST -
167.248.133.36 - - [07/Oct/2020 14:16:28] "[37mGET / HTTP/1.1[0m" 200 -
167.248.133.36 - - [07/Oct/2020 14:16:28] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.70 - - [07/Oct/2020 17:27:02] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.70 - - [07/Oct/2020 17:27:03] "[37mGET /expense_data?_=1602091621851 HTTP/1.1[0m" 200 -
183.83.146.70 - - [07/Oct/2020 17:27:03] "[37mGET /current_expense_data?_=1602091621852 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 06:40:25] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 06:40:25] "[37mGET /expense_data?_=1602139224239 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 06:40:25] "[37mGET /current_expense_data?_=1602139224240 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 06:40:25] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
157.47.107.194 - - [08/Oct/2020 11:25:08] "[37mGET / HTTP/1.1[0m" 200 -
157.47.107.194 - - [08/Oct/2020 11:25:14] "[37mGET / HTTP/1.1[0m" 200 -
157.47.107.194 - - [08/Oct/2020 11:25:23] "[37mGET /expense_data?_=1602156321588 HTTP/1.1[0m" 200 -
157.47.107.194 - - [08/Oct/2020 11:25:23] "[37mGET /current_expense_data?_=1602156321589 HTTP/1.1[0m" 200 -
157.47.107.194 - - [08/Oct/2020 11:25:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.222 - - [08/Oct/2020 11:25:40] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 11:25:46] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 11:25:46] "[37mGET /expense_data?_=1602156344602 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 11:25:46] "[37mGET /current_expense_data?_=1602156344603 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 11:26:02] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 11:26:07] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 11:26:08] "[37mGET /expense_data?_=1602156366399 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 11:26:08] "[37mGET /current_expense_data?_=1602156366400 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 15:22:00] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 15:22:00] "[37mGET /expense_data?_=1602170518940 HTTP/1.1[0m" 200 -
183.83.147.222 - - [08/Oct/2020 15:22:00] "[37mGET /current_expense_data?_=1602170518941 HTTP/1.1[0m" 200 -
162.142.125.51 - - [08/Oct/2020 20:09:42] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03ý\x14íîÚ\x9a³Fã«ó[q%\x9d"ó\x1b\x8b\x91};ÖpH¼aã¤l\x90G\x00\x00\x1aÀ/À+À\x11À\x07À\x13À')
162.142.125.51 - - [08/Oct/2020 20:09:42] "[35m[1m {  wýíîÚ³Fã«ó[q%"ó};ÖpH¼aã¤lG  À/À+ÀÀÀÀ	ÀÀ[0m" HTTPStatus.BAD_REQUEST -
162.142.125.51 - - [08/Oct/2020 20:09:43] "[37mGET / HTTP/1.1[0m" 200 -
162.142.125.51 - - [08/Oct/2020 20:09:44] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 02:41:36] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 02:41:37] "[37mGET /expense_data?_=1602211295457 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 02:41:37] "[37mGET /current_expense_data?_=1602211295458 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 02:41:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.3 - - [09/Oct/2020 02:41:39] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 02:41:40] "[37mGET /expense_data?_=1602211298342 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 02:41:40] "[37mGET /current_expense_data?_=1602211298343 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.3 - - [09/Oct/2020 04:32:18] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:32:19] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.3 - - [09/Oct/2020 04:32:19] "[37mGET /expense_data?_=1602217938822 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:32:19] "[37mGET /current_expense_data?_=1602217938823 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.3 - - [09/Oct/2020 04:44:14] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:44:14] "[37mGET /expense_data?_=1602218653943 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:44:14] "[37mGET /current_expense_data?_=1602218653944 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:45:42] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:45:47] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:45:48] "[37mGET /expense_data?_=1602218747539 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 04:45:48] "[37mGET /current_expense_data?_=1602218747540 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:11:08] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:11:08] "[37mGET /expense_data?_=1602245468264 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:11:08] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.3 - - [09/Oct/2020 12:11:08] "[37mGET /current_expense_data?_=1602245468265 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:11:39] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:11:44] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:11:45] "[37mGET /expense_data?_=1602245504505 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:11:45] "[37mGET /current_expense_data?_=1602245504506 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:12:07] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:12:12] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:12:12] "[37mGET /expense_data?_=1602245532313 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:12:12] "[37mGET /current_expense_data?_=1602245532314 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:12:57] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:13:02] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:13:02] "[37mGET /expense_data?_=1602245582325 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:13:02] "[37mGET /current_expense_data?_=1602245582326 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:15:58] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:15:59] "[37mGET /expense_data?_=1602245757344 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:15:59] "[37mGET /current_expense_data?_=1602245757345 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:16:09] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:16:14] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:16:14] "[37mGET /expense_data?_=1602245772937 HTTP/1.1[0m" 200 -
183.83.147.3 - - [09/Oct/2020 12:16:14] "[37mGET /current_expense_data?_=1602245772938 HTTP/1.1[0m" 200 -
183.83.147.249 - - [09/Oct/2020 16:38:33] "[37mGET /expense_data?_=1602261511200 HTTP/1.1[0m" 200 -
183.83.147.249 - - [09/Oct/2020 16:38:33] "[37mGET /current_expense_data?_=1602261511201 HTTP/1.1[0m" 200 -
183.83.147.249 - - [09/Oct/2020 16:38:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.249 - - [09/Oct/2020 16:39:01] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.249 - - [09/Oct/2020 16:39:02] "[37mGET /expense_data?_=1602261540380 HTTP/1.1[0m" 200 -
183.83.147.249 - - [09/Oct/2020 16:39:02] "[37mGET /current_expense_data?_=1602261540381 HTTP/1.1[0m" 200 -
192.35.169.48 - - [10/Oct/2020 00:28:57] "[37mGET / HTTP/1.1[0m" 200 -
85.93.20.170 - - [10/Oct/2020 00:39:59] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
85.93.20.170 - - [10/Oct/2020 00:39:59] "[35m[1m  /*à     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
157.44.18.64 - - [10/Oct/2020 03:06:49] "[37mGET / HTTP/1.1[0m" 200 -
157.44.18.64 - - [10/Oct/2020 03:06:49] "[37mGET /expense_data?_=1602299207769 HTTP/1.1[0m" 200 -
157.44.18.64 - - [10/Oct/2020 03:06:49] "[37mGET /current_expense_data?_=1602299207770 HTTP/1.1[0m" 200 -
85.93.20.170 - - [10/Oct/2020 06:06:39] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
85.93.20.170 - - [10/Oct/2020 06:06:39] "[35m[1m  /*à     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
157.44.12.42 - - [10/Oct/2020 12:04:06] "[37mGET / HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:08] "[37mGET /expense_data?_=1602331446430 HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:08] "[37mGET /current_expense_data?_=1602331446431 HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:18] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:23] "[37mGET / HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:24] "[37mGET /expense_data?_=1602331462317 HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:24] "[37mGET /current_expense_data?_=1602331462318 HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:36] "[37mGET / HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:37] "[37mGET /expense_data?_=1602331475277 HTTP/1.1[0m" 200 -
157.44.12.42 - - [10/Oct/2020 12:04:37] "[37mGET /current_expense_data?_=1602331475278 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 02:51:23] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 02:51:23] "[37mGET /expense_data?_=1602384681858 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 02:51:23] "[37mGET /current_expense_data?_=1602384681859 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:29:01] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:29:03] "[37mGET /expense_data?_=1602412140710 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:29:03] "[37mGET /current_expense_data?_=1602412140711 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:29:12] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:29:17] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:29:17] "[37mGET /expense_data?_=1602412155748 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:29:17] "[37mGET /current_expense_data?_=1602412155749 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:31:24] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:31:30] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:31:30] "[37mGET /expense_data?_=1602412288192 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:31:30] "[37mGET /current_expense_data?_=1602412288193 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:32:03] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:32:09] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:32:09] "[37mGET /expense_data?_=1602412327405 HTTP/1.1[0m" 200 -
183.83.147.180 - - [11/Oct/2020 10:32:09] "[37mGET /current_expense_data?_=1602412327406 HTTP/1.1[0m" 200 -
198.20.87.98 - - [11/Oct/2020 13:25:37] "[37mGET / HTTP/1.1[0m" 200 -
198.20.87.98 - - [11/Oct/2020 13:25:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
45.146.164.179 - - [11/Oct/2020 14:32:48] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
45.146.164.179 - - [11/Oct/2020 14:32:48] "[35m[1m  /*à     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
45.146.164.179 - - [11/Oct/2020 22:09:17] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
45.146.164.179 - - [11/Oct/2020 22:09:17] "[35m[1m  /*à     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
183.83.146.138 - - [12/Oct/2020 00:35:52] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.138 - - [12/Oct/2020 00:35:53] "[37mGET /expense_data?_=1602462950973 HTTP/1.1[0m" 200 -
183.83.146.138 - - [12/Oct/2020 00:35:53] "[37mGET /current_expense_data?_=1602462950974 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/meta.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/meta.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/meta.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/meta.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/config/__pycache__/__init__.cpython-36.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/cron_main.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.146.138 - - [13/Oct/2020 05:49:56] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.138 - - [13/Oct/2020 05:49:57] "[37mGET /expense_data?_=1602568196512 HTTP/1.1[0m" 200 -
183.83.146.138 - - [13/Oct/2020 05:49:57] "[37mGET /current_expense_data?_=1602568196513 HTTP/1.1[0m" 200 -
183.83.146.138 - - [13/Oct/2020 05:49:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
5.8.18.88 - - [13/Oct/2020 05:53:56] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
5.8.18.88 - - [13/Oct/2020 05:53:56] "[35m[1m  /*à     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
5.8.18.88 - - [13/Oct/2020 07:34:53] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
5.8.18.88 - - [13/Oct/2020 07:34:53] "[35m[1m  /*à     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
5.8.18.88 - - [13/Oct/2020 09:29:27] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
5.8.18.88 - - [13/Oct/2020 09:29:27] "[35m[1m  /*à     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
192.35.169.48 - - [13/Oct/2020 23:44:40] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 02:49:28] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 02:49:29] "[37mGET /expense_data?_=1602643768360 HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 02:49:29] "[37mGET /current_expense_data?_=1602643768361 HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 04:59:03] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 04:59:04] "[37mGET /expense_data?_=1602651542776 HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 04:59:04] "[37mGET /current_expense_data?_=1602651542777 HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 04:59:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.147.251 - - [14/Oct/2020 05:06:48] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 05:06:49] "[37mGET /expense_data?_=1602652007898 HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 05:06:49] "[37mGET /current_expense_data?_=1602652007899 HTTP/1.1[0m" 200 -
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.147.251 - - [14/Oct/2020 06:05:40] "[37mGET / HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 06:05:41] "[37mGET /expense_data?_=1602655540065 HTTP/1.1[0m" 200 -
183.83.147.251 - - [14/Oct/2020 06:05:41] "[37mGET /current_expense_data?_=1602655540066 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:23] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:24] "[37mGET /expense_data?_=1602738203768 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:24] "[37mGET /current_expense_data?_=1602738203769 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:24] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.146.205 - - [15/Oct/2020 05:03:39] "[35m[1mPOST /addDetails HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/Expense-Tracker-App/main_mobile.py", line 183, in addDetails
    cursor.execute(cash_query,(datetime.now().strftime('%Y-%m-%d %H:%M:%S'),data['item_type'],))
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'None' in 'field list'
183.83.146.205 - - [15/Oct/2020 05:03:39] "[37mGET /addDetails?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:39] "[37mGET /addDetails?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:39] "[37mGET /addDetails?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:40] "[37mGET /addDetails?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:40] "[37mGET /addDetails?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:03:40] "[37mGET /addDetails?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:05:52] "[37mGET /expense_data?_=1602738351975 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:05:53] "[37mGET /current_expense_data?_=1602738351976 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:06:29] "[37mPOST /addDetails HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:06:34] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:06:34] "[37mGET /expense_data?_=1602738393756 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:06:34] "[37mGET /current_expense_data?_=1602738393757 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:06:53] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:06:53] "[37mGET /expense_data?_=1602738412786 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:06:53] "[37mGET /current_expense_data?_=1602738412787 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:07:06] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:07:06] "[37mGET /expense_data?_=1602738425840 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:07:06] "[37mGET /current_expense_data?_=1602738425841 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:07:41] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:07:42] "[37mGET /expense_data?_=1602738461334 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:07:42] "[37mGET /current_expense_data?_=1602738461335 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:38:23] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:38:24] "[37mGET /expense_data?_=1602740303434 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:38:24] "[37mGET /current_expense_data?_=1602740303435 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 05:38:24] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
 * Detected change in '/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/python-config.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/database.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/decrypt.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/__pycache__/helper_functions.cpython-36.pyc', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/helper_functions.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Detected change in '/home/ubuntu/Expense-Tracker-App/main_mobile.py', reloading
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 162-659-695
183.83.146.205 - - [15/Oct/2020 06:57:36] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 06:57:37] "[35m[1mGET /expense_data?_=1602745055366 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/Expense-Tracker-App/main_mobile.py", line 81, in expense_data
    temp_df['Unit of Measurement'] = ['Bottle','Units','INR','INR','Bottle','INR','INR','INR','INR']
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/pandas/core/frame.py", line 3487, in __setitem__
    self._set_item(key, value)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/pandas/core/frame.py", line 3564, in _set_item
    value = self._sanitize_column(key, value)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/pandas/core/frame.py", line 3749, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "/home/ubuntu/envs/expense/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 612, in sanitize_index
    raise ValueError("Length of values does not match length of index")
ValueError: Length of values does not match length of index
183.83.146.205 - - [15/Oct/2020 06:57:37] "[37mGET /current_expense_data?_=1602745055367 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 06:57:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
183.83.146.205 - - [15/Oct/2020 06:58:10] "[37mGET / HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 06:58:11] "[37mGET /expense_data?_=1602745089268 HTTP/1.1[0m" 200 -
183.83.146.205 - - [15/Oct/2020 06:58:11] "[37mGET /current_expense_data?_=1602745089269 HTTP/1.1[0m" 200 -
